### ISSUE TITLE
qgsfieldcombobox.h problem in the ui file

### ISSUE THREAD

**Issue by mlaloux** [elpaso/qgis-formawarevaluerelationwidget#1]
In Mac OS X, you need to change  `qgsfieldcombobox.h` by `qgis.gui` in the FormAwareValueRelationConfigDlg.ui file:

```
   <customwidgets>
            <customwidget>
                   <class>QgsFieldComboBox</class>
                   <extends>QComboBox</extends>
                  <header>qgis.gui</header>
            </customwidget>
            <customwidget>
                  <class>QgsMapLayerComboBox</class>
                  <extends>QComboBox</extends>
                <header>qgis.gu</header>
            </customwidget>
   </customwidgets>
```

If not there is an error:

```
     ImportError: No module named qgsfieldcombobox 
```

The solution is explained in [GIS SE: My plugins crashes with No module named qgsprojectionselectionwidget” in Windows](http://gis.stackexchange.com/questions/164111/my-plugins-crashes-with-no-module-named-qgsprojectionselectionwidget-in-window)

**Comment by elpaso** [comment]
@mlaloux fixed in 1.1 please test it

**Comment by mlaloux** [comment]
Thanks, it's work now with the correction.

**Comment by elpaso** [comment]
Thank **you** for reporting this issue!
