### ISSUE TITLE
Widget doesn't work in attribute table (error or feature request ?)

### ISSUE THREAD

**Issue by Frederikssund** [elpaso/qgis-formawarevaluerelationwidget#10]
If you open an attribute window where the layer is in edit mode and try to change the value in one of the columns that's controlled by the formaware relation widget, the widget will show all the possible values from the lookup layer, i.e. the dynamic filter function doesn't work as expected.

Step to reproduce:
- Have a project with a layer that uses the widget.
- Use the identfy tool and try to change a value in a column controlled by the widget - This works.
- Start the attribute window with the same layer as before (still in edit mode) and try to change the value in the column controlled....
- The drop-down box in the attribute window for the column is filled with all the possible values from the lookup table. There is no filtering done.  

I can see, that ver 1.4 explictly disables this function, because it results in crash. It would be better to enable the function and solve the "crash" problem in another way.

**Comment by elpaso** [comment]
That's the expected behavior, unfortunately the dynamic filter in the attribute table is not currenlty possible from a plugin without changing the core of QGIS.
