### ISSUE TITLE
Qgis 2.18 - Plugin only work in form mode not attribute table

### ISSUE THREAD

**Issue by amandine-sahl** [elpaso/qgis-formawarevaluerelationwidget#16]
OK with form
![image](https://user-images.githubusercontent.com/3088650/31667650-5f0681f4-b350-11e7-90db-f35e502f38e8.png)

Not ok with attribute table even in form mode
![image](https://user-images.githubusercontent.com/3088650/31667698-7e7d4b44-b350-11e7-93a4-3cb90d62fd7d.png)

**Comment by elpaso** [comment]
That is a known limitation
