### ISSUE TITLE
The Form Value Relation is not installed properly

### ISSUE THREAD

**Issue by 9ls1** [elpaso/qgis-formawarevaluerelationwidget#3]
Thanks for creating this widget that I really would like to use.
But, something's wrong. I'm using QGIS 2.12.3 having Norwegian as the language. After installing the plugin, the widget name appears in the list but the "widget" is empty - no input is shown.
![2016-02-22 20_13_15-rediger egenskaper for programtillegg - veg1 2212-2_f](https://cloud.githubusercontent.com/assets/10632163/13229371/d8e249e4-d9a0-11e5-9a64-8430e9412328.png)
Any idea how to solve this? Install English version of QGIS? (the Norwegian version is installed automatically, I'm not choosing language during installation.)

**Comment by elpaso** [comment]
Honestly, I checked only english and italian and there are no problems with both.

You can change temporarily your language under settings -> options  -> locale (and restart QGIS).

Please let me know if that works.

**Comment by 9ls1** [comment]
Beautiful! That did the trick, thanks!

**Comment by elpaso** [comment]
Still, I would like to know why that happens...

**Comment by elpaso** [comment]
Can you please try to change:
https://github.com/elpaso/qgis-formawarevaluerelationwidget/blob/master/FormAwareValueRelationWidget.py#L51

to just return text?

like:

```
def tr(text):
    return text
```

**Comment by luipir** [comment]
works under Ubuntu 15.10 with spanish translation

**Comment by elpaso** [comment]
@luipir thanks for testing, so far seems to fail in norvegian (windows) and finnish (unknown O.S.)

**Comment by 9ls1** [comment]
@elpaso changing line 51 as you suggest seems to work. I carried out the changes in code, set the language to Norwegian and restartet QGIS. Form Value Relation appeared correctly:
![2016-02-22 21_22_28-the form value relation is not installed properly issue 3 elpaso_qgis-forma](https://cloud.githubusercontent.com/assets/10632163/13231507/7913af9e-d9aa-11e5-8a9d-1d59e907b01b.png)

**Comment by elpaso** [comment]
Thanks for testing... I'll check it out and make a new release!
