### ISSUE TITLE
Feature Count and Python errors

### ISSUE THREAD

**Issue by CasperBertelsen** [elpaso/qgis-formawarevaluerelationwidget#4]
If I try to change the content of an attribute after I’ve created the feature my program crashes as I double-click on the attribute field with a pop-up windows saying
Minidump written to C: … \Temp\qgis-20160310-071702-9988-4565-99ac688.dmp

As well when I delete features they are kept in ‘Show feature Count’ and I get this Python-error:

2016-03-10T07:12:03 1   Traceback (most recent call last):
File “C:/Users/CasperBJ/.qgis2/python/plugins\FormAwareValueRelationWidget\FormAwareValueRelationWidget.py”, line 357, in createCache
layer = QgsMapLayerRegistry.instance().mapLayer( self.config( “Layer” ) )
RuntimeError: wrapped C/C++ object of type FormAwareValueRelationWidgetWrapper has been deleted

2016-03-10T07:12:24 1   Traceback (most recent call last):
File “C:/Users/CasperBJ/.qgis2/python/plugins\FormAwareValueRelationWidget\FormAwareValueRelationWidget.py”, line 357, in createCache
layer = QgsMapLayerRegistry.instance().mapLayer( self.config( “Layer” ) )
RuntimeError: wrapped C/C++ object of type FormAwareValueRelationWidgetWrapper has been deleted

2016-03-10T07:12:37 1   Traceback (most recent call last):
File “C:/Users/CasperBJ/.qgis2/python/plugins\FormAwareValueRelationWidget\FormAwareValueRelationWidget.py”, line 357, in createCache
layer = QgsMapLayerRegistry.instance().mapLayer( self.config( “Layer” ) )
RuntimeError: wrapped C/C++ object of type FormAwareValueRelationWidgetWrapper has been deleted

2016-03-10T07:12:37 1   Traceback (most recent call last):
File “C:/Users/CasperBJ/.qgis2/python/plugins\FormAwareValueRelationWidget\FormAwareValueRelationWidget.py”, line 357, in createCache
layer = QgsMapLayerRegistry.instance().mapLayer( self.config( “Layer” ) )
RuntimeError: wrapped C/C++ object of type FormAwareValueRelationWidgetWrapper has been deleted

2016-03-10T07:13:52 1   Traceback (most recent call last):
File “C:/Users/CasperBJ/.qgis2/python/plugins\FormAwareValueRelationWidget\FormAwareValueRelationWidget.py”, line 357, in createCache
layer = QgsMapLayerRegistry.instance().mapLayer( self.config( “Layer” ) )
RuntimeError: wrapped C/C++ object of type FormAwareValueRelationWidgetWrapper has been deleted

**Comment by CasperBertelsen** [comment]
Now that I've updated my QGIS to 2.14 I don't seem to have the problem with feature count moving up as I delete features - But the python error still occurs

**Comment by elpaso** [comment]
Thanks for reporting this issue, can you please check the version I've just uploaded?
Unfortunately I had to disable the dynamic filters when the widget is accessed from the attribute table, there is a problem with widgets being deleted from the delegate with "deleteLater", there is no way to overcome this from a plugin.
I hope this will prevent errors, the plugin will work just like the standard value relation widget when accessed through the attribute table.

**Comment by CasperBertelsen** [comment]
I no longer get the python error everytime i delete features and the attribute table seems to be working with a select menu.
