### ISSUE TITLE
Problem with QGIS 2.12.2

### ISSUE THREAD

**Issue by irishfrog** [elpaso/qgis-formawarevaluerelationwidget#5]
Hello,
I just want to let you know that I use the 1.4 version of the plugin Form Value relation with QGIS 2.12.2 and windows 7 (With QGIS in french language). The filter doesn't seems to work. (I also try with your example project)

I install the 2.14 version of QGIS and everything works well with the same project.

**Comment by pcav** [comment]
I'd suggest to close this, as 2.12 is now obsolete and not supported
